# Generated by Django 5.1.4 on 2025-01-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ARModel",
            fields=[
                (
                    "modelId",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("qrurl", models.URLField()),
                ("url", models.URLField()),
            ],
        ),
    ]
